---
title: "Data_analysis"
output: html_document
---


## Description of the data

```{r, warning=FALSE, echo=FALSE}
library(data.table)
library(here)
load(here("data", "ASTER.RData"))
library(viridis)
library(geoR)
```

### Spatial plots
```{r, warning=FALSE}
library(gridExtra) 
 # Spatial distribution of temperature
 library(ggplot2)
emis = ggplot(dt, aes(lon, lat)) +
  geom_raster(aes(fill = emis)) +
  xlab("longitude") +
  ylab("latitude") +
  guides(fill = guide_legend(title = "emissivity")) +
  ggtitle("Spatial Emissivity Distribution") +
  coord_fixed()
 
ndvi = ggplot(dt, aes(lon, lat)) +
 geom_raster(aes(fill = ndvi)) +
 xlab("longitude") +
 ylab("latitude") +
 guides(fill = guide_legend(title = "NDVI")) +
 ggtitle("Spatial ndvi Distribution") +
 coord_fixed()

temp =  ggplot(dt, aes(lon, lat)) +
 geom_raster(aes(fill = temp)) +
 xlab("longitude") +
 ylab("latitude") +
 guides(fill = guide_legend(title = "temperature")) +
 ggtitle("Spatial temperature Distribution") +
 coord_fixed()

#elev = ggplot(dt, aes(lon, lat)) +
 #geom_raster(aes(fill = elev)) +
 #xlab("longitude") +
 #ylab("latitude") +
 #guides(fill = guide_legend(title = "elevation")) +
 #ggtitle("Spatial elevation Distribution") +
 #coord_fixed()


# Combine plots and save: 
library(patchwork)
combined_plot <- emis | ndvi | temp 
#ggsave("C:/Lecture slides/Lecture slides/Lecture Slides/Winter 2025/Biostat 815/Quiz2/svc/figures/spatial_horizontal_stack.png",
 #      combined_plot, width = 15, height = 5, dpi = 300)

ggsave("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/spatial_horizontal_stack.png",
       combined_plot, width = 30, height = 10, dpi = 300)

```

### Semivariograms
```{r}
# subset data further for more efficient semivariogram analysis
lat.sub = dt[, unique(lat)]
lat.sub = lat.sub[seq(1, length(lat.sub), by = 2)]
lon.sub = dt[, unique(lon)]
lon.sub = lon.sub[seq(1, length(lon.sub), by = 2)]
dt.sub = dt[lat %in% lat.sub & lon %in% lon.sub]
dt.sub = dt.sub[complete.cases(dt.sub[, c("lat", "lon", "ndvi", "temp")]), ]
# semivariogram of emissivity
sv = variog(
coords = cbind(dt.sub[!is.na(emis), lat], dt.sub[!is.na(emis), lon]),
data = dt.sub[!is.na(emis), emis]
)
sv.dt = data.table(
dists = sv$u,
variogram = sv$v,
npairs = sv$n,
sd = sv$sd
)

emis_sv = ggplot(sv.dt, aes(x = dists, y = variogram)) +
geom_point() +
labs(title = "Emissivity semivariogram")

# semivariogram of NDVI
sv = variog(
coords = cbind(dt.sub[, lat], dt.sub[, lon]),
data = dt.sub[, ndvi]
)
sv.dt = data.table(
dists = sv$u,
variogram = sv$v,
npairs = sv$n,
sd = sv$sd
)

ndvi_sv = ggplot(sv.dt, aes(x = dists, y = variogram)) +
geom_point() +
labs(title = "NDVI semivariogram")


# semivariogram of temp
sv = variog(
coords = cbind(dt.sub[, lat], dt.sub[, lon]),
data = dt.sub[, temp]
)
sv.dt = data.table(
dists = sv$u,
variogram = sv$v,
npairs = sv$n,
sd = sv$sd
)

temp_sv = ggplot(sv.dt, aes(x = dists, y = variogram)) +
geom_point() +
labs(title = "Temperature semivariogram")

# semivariogram of Elev
#sv = variog(
#coords = cbind(dt.sub[, lat], dt.sub[, lon]),
#data = dt.sub[, elev]
#)
#sv.dt = data.table(
#dists = sv$u,
#variogram = sv$v,
#npairs = sv$n,
#sd = sv$sd
#)

#elev_sv = ggplot(sv.dt, aes(x = dists, y = variogram)) +
#geom_point() +
#labs(title = "ELevation semivariogram")

combined_plot_sv <- emis_sv | ndvi_sv|temp_sv 
ggsave("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/semivariograms.png",
       combined_plot_sv, width = 30, height = 10, dpi = 300)


```

### Model Fitting
```{r}
library(svc)

Y = dt$temp
X = as.matrix(dt[, c("ndvi", "emis","elev")])
X = cbind(1, X)
coords = as.matrix(dt[, c("lat", "lon")]) 

knot_results = simpleknots(
  Y = Y,
  X = X,
  coords = coords,
  k = 30 
)

# Extract knot components
Y_knots = knot_results$Y_knots
X_knots = knot_results$X_knots
knots = knot_results$knots

missing = apply(X_knots, 1, function(x) any(is.na(x))) | is.na(Y_knots)
# 
Y_knots = Y_knots[!missing]
X_knots = X_knots[!missing,]
knots = knots[!missing,]

p = ncol(X_knots)

# Define phi range
phi_lower = rep(0.001, p)
phi_upper = rep(500, p)

fit = svclm(
  Y = Y,
  X = X,
  coords = coords,
  Y_knots = Y_knots,
  X_knots = X_knots,
  knots = knots,
  phi_lower = phi_lower,
  phi_upper = phi_upper,
  mcmc = 5000
)


saveRDS(fit, file = "fit_model.rds")
```



##  CONVERGENCE DIAGNOSTICS

```{r}
library(tidyverse)
fit = readRDS("fit_model.rds")

burnin <- 4000

# Subset after burn-in
phi_samples <- fit$phi_samples[(burnin + 1):nrow(fit$phi_samples), ]
sigmasq_samples <- fit$sigmasq_samples[(burnin + 1):nrow(fit$sigmasq_samples), ]
tausq_samples <- fit$tausq_samples[(burnin + 1):length(fit$tausq_samples)]


trace_data <- data.frame(
  iteration = 1:nrow(phi_samples),
  phi_1 = phi_samples[, 1],
  phi_2 = phi_samples[, 2],
  phi_3 = phi_samples[, 3],
  sigmasq_1 = sigmasq_samples[, 1],
  sigmasq_2 = sigmasq_samples[, 2],
  sigmasq_3 = sigmasq_samples[, 3],
  tausq = tausq_samples
)


# Pivot to long format
trace_long <- trace_data %>%
  pivot_longer(-iteration, names_to = "parameter", values_to = "value")

# Plot
traceplots = ggplot(trace_long, aes(x = iteration, y = value)) +
  geom_line(alpha = 0.7) +
  facet_wrap(~ parameter, scales = "free_y", ncol = 2) +
  labs(title = "MCMC Trace Plots", x = "Iteration", y = "Parameter Value") +
  theme_minimal()

ggsave("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/traceplots.png",
       traceplots, width = 20, height = 10, dpi = 300)
```

```{r, warning=FALSE}
burnin <- 4000
w_postburn <- fit$w_samples[(burnin + 1):dim(fit$w_samples)[1], , ]

w_means_df <- data.frame(
  lat = coords[, "lat"],
  lon = coords[, "lon"],
  w1 = colMeans(w_postburn[, , 1]),
  w2 = colMeans(w_postburn[, , 2]),
  w3 = colMeans(w_postburn[, , 3])
)

library(ggplot2)
library(scico)

A = ggplot(w_means_df, aes(x = lon, y = lat)) +
  geom_raster(aes(fill = w2)) +
  xlab("Longitude") +
  ylab("Latitude") +
  guides(fill = guide_legend(title = "NDVI Effect")) +
  ggtitle("Spatial Distribution of Posterior Mean (NDVI)") +
  coord_fixed() +
  scico::scale_fill_scico(palette = "tofino") +
  theme_minimal()



B = ggplot(w_means_df, aes(x = lon, y = lat)) +
  geom_raster(aes(fill = w3)) +
  xlab("Longitude") +
  ylab("Latitude") +
  guides(fill = guide_legend(title = "Emissivity Effect")) +
  ggtitle("Spatial Distribution of Posterior Mean (Emissivity)") +
  coord_fixed() +
  scico::scale_fill_scico(palette = "tofino") +
  theme_minimal()


library(patchwork)
combined_plot_m = A | B 
ggsave("~/svc/figures/model_means.png",
       combined_plot_m, width = 15, height = 5, dpi = 300)
```

```{r}
# Save Beta NDVI - Location 62
png("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/beta_ndvi_location62.png", width = 800, height = 600)
plot(w_postburn[, 62, 2], type = 'l',
     main = "Beta NDVI - Location 62", ylab = "Coefficient Value")
dev.off()

# Save Beta Emissivity - Location 62
png("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/beta_emis_location62.png", width = 800, height = 600)
plot(w_postburn[, 62, 3], type = 'l',
     main = "Beta Emissivity - Location 62", ylab = "Coefficient Value")
dev.off()
```
### Acceptance rate
```{r}
total_accepted <- sum(fit$phi_acceptance == 1)
total_elements <- length(fit$phi_acceptance)
acceptance_rate <- total_accepted / total_elements
acceptance_rate
```

### Plot of Knot locations
```{r}
# Convert knots to a data frame
knot_df = data.frame(
  lat = knots[, 1],
  lon = knots[, 2]
)

kts  = ggplot(dt, aes(x = lon, y = lat)) +
  geom_raster(aes(fill = temp)) + 
  geom_point(data = knot_df, aes(x = lon, y = lat),
             color = "black", fill = "black", size = 1.2, shape = 4, stroke = 0.3) +
  xlab("Longitude") +
  ylab("Latitude") +
  guides(fill = guide_legend(title = "temp")) +  # Change legend title as needed
  ggtitle("Spatial Distribution with Knot Locations(Crosses Represent Knots)") +
  coord_fixed() +
  scico::scale_fill_scico(palette = "bam") +
  theme_minimal()

ggsave("~/svc/figures/knot_locations.png",
       kts, width = 15, height = 5, dpi = 300)
```


### Predictions

```{r}
missing_idx = which(is.na(dt$temp))

X = as.matrix(dt[, c("ndvi", "emis")])
X = cbind(1, X)
X_missing <- X[missing_idx, ]  # rows with NA in temp
w_missing <- w_means_df[missing_idx, c("w1", "w2", "w3")]

temp_pred <- rowSums(X_missing * as.matrix(w_missing))


coords_missing <- coords[missing_idx, ]

pred_df <- data.frame(
  lon = coords_missing[, "lon"],
  lat = coords_missing[, "lat"],
  temp_pred = temp_pred
)

library(ggplot2)

ggplot(pred_df, aes(lon, lat)) +
 geom_raster(aes(fill = temp_pred)) +
 xlab("longitude") +
 ylab("latitude") +
 guides(fill = guide_legend(title = "Predicted temperature")) +
 ggtitle("Predicted temperature Distribution") +
 coord_fixed()

ggsave("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/traceplots.png",
       traceplots, width = 20, height = 10, dpi = 300)
```
### Predcitons for whole temperature surface
```{r}
X_full <- as.matrix(dt[, c("ndvi", "emis")])
X_full <- cbind(1, X_full)  # Add intercept
w_all <- w_means_df[, c("w1", "w2", "w3")]
dt$temp_pred_full <- rowSums(X_full * as.matrix(w_all))

pred_temp = ggplot(dt, aes(lon, lat)) +
 geom_raster(aes(fill = temp_pred_full)) +
 xlab("longitude") +
 ylab("latitude") +
 guides(fill = guide_legend(title = "Predicted temperature")) +
 ggtitle("Predicted temperature Distribution") +
 coord_fixed()

library(patchwork)
combined_plot_pred = temp | pred_temp

ggsave("C:/Lecture Slides/Winter 2025/Biostat 815/svc/figures/predictions.png",
       combined_plot_pred, width = 20, height = 10, dpi = 300)

```
