# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svclm_cpp <- function(Y, X, s, Y_knots, X_knots, knots, w_knots_start, sigmasq_start, a_sigmasq, b_sigmasq, tausq_start, a_tausq, b_tausq, phi_start, phi_lower, phi_upper, phi_proposal_sd_start, phi_target_acceptance, mcmc) {
    .Call(`_svc_svclm_cpp`, Y, X, s, Y_knots, X_knots, knots, w_knots_start, sigmasq_start, a_sigmasq, b_sigmasq, tausq_start, a_tausq, b_tausq, phi_start, phi_lower, phi_upper, phi_proposal_sd_start, phi_target_acceptance, mcmc)
}

