# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_svclm_theta <- function(Y, X, coords, beta_start, tausq_start, sigmasq_start, phi_start, tausq_proposal_sd, sigmasq_proposal_sd, phi_proposal_sd, phi_lower, phi_upper, a_tausq, b_tausq, a_sigmasq, b_sigmasq, mcmc = 1000L) {
    .Call(`_svc_new_svclm_theta`, Y, X, coords, beta_start, tausq_start, sigmasq_start, phi_start, tausq_proposal_sd, sigmasq_proposal_sd, phi_proposal_sd, phi_lower, phi_upper, a_tausq, b_tausq, a_sigmasq, b_sigmasq, mcmc)
}

