# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svclm <- function(Y, X, s, Y_knots, X_knots, knots, beta_knots_start, phi_beta_start, sigmasq_beta_start, tausq_start, phi_beta_proposal_sd, phi_beta_lower, phi_beta_upper, a_beta, b_beta, a_t, b_t, mcmc = 1000L) {
    .Call(`_svc_svclm`, Y, X, s, Y_knots, X_knots, knots, beta_knots_start, phi_beta_start, sigmasq_beta_start, tausq_start, phi_beta_proposal_sd, phi_beta_lower, phi_beta_upper, a_beta, b_beta, a_t, b_t, mcmc)
}

